"""initial_schema

Revision ID: accf1ccf46b0
Revises: 
Create Date: 2025-12-07 17:59:47.592374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'accf1ccf46b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_conversation_id'), table_name='document')
    op.drop_constraint(op.f('uq_document_user_provider_external'), 'document', type_='unique')
    op.drop_constraint(op.f('document_conversation_id_fkey'), 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'conversations', ['conversation_id'], ['id'])
    op.create_index(op.f('ix_document_embeddings_document_id'), 'document_embeddings', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_id'), 'document_embeddings', ['id'], unique=False)
    op.create_index(op.f('ix_document_embeddings_user_id'), 'document_embeddings', ['user_id'], unique=False)
    op.drop_constraint(op.f('messages_user_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('idx_users_auth_user_id'), table_name='users')
    op.create_index(op.f('ix_users_auth_user_id'), 'users', ['auth_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_auth_user_id'), table_name='users')
    op.create_index(op.f('idx_users_auth_user_id'), 'users', ['auth_user_id'], unique=False)
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_user_id_fkey'), 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_embeddings_user_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_id'), table_name='document_embeddings')
    op.drop_index(op.f('ix_document_embeddings_document_id'), table_name='document_embeddings')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key(op.f('document_conversation_id_fkey'), 'document', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_document_user_provider_external'), 'document', ['user_id', 'provider', 'external_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_document_conversation_id'), 'document', ['conversation_id'], unique=False)
    # ### end Alembic commands ###
